routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resource('course', 'CourseController');

app/Course.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    //

    protected $fillable = ['code', 'name', 'description', 'credit_hour', 'instructor', 'price'];
    protected $guarded = ['id', 'created_at', 'update_at'];
    protected $table = 'courses';
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CourseController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Course;
class CourseController extends Controller
{
    //
    public function index() {
        $courses = Course::all();
        $total = Course::all()->count();
        return view('list-course', compact('courses', 'total'));
    }

    public function create() {
        return view('include-course');
    }

    public function store(Request $request) {
        $course = new Course;
        $course->id = $request->id;
        $course->code = $request->code;
        $course->name = $request->name;
        $course->description = $request->description;
        $course->credit_hour = $request->credit_hour;
        $course->instructor = $request->instructor;
        $course->price = $request->price;
        $course->save();
        return redirect()->route('course.index')->with('message','Curso criado com sucesso');
        
    }

    public function show($id){

    }

    public function edit($id){
        $course = Course::findOrFail($id);
        return view('alter-course', compact('course'));
    }

    public function update(Request $request, $id){
        $course = Course::findOrFail($id);
        $course->code = $request->code;
        $course->name = $request->name;
        $course->description = $request->description;
        $course->credit_hour = $request->credit_hour;
        $course->instructor = $request->instructor;
        $course->price = $request->price;
        $course->save();
        return redirect()->route('course.index')->with('message','Curso alterado com sucesso!');
        
    }

    public function destroy($id){
        $course = Course::findOrFail($id);
        $course->delete();
        return redirect()->route('course.index')->with('message', 'Curso excluido com sucesso!');
    }


}

resources/views/alter-course.blade.php
@extends('default')

@section('content')
<div class="container-fluid">
            <hr/>
            <h3 class="page-item">Editar cursos</h3>
            <div class="col-md-12"
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ url('course/') }}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Editar</li>
                    </ol>
                </nav>
            </div>
            <hr/>
            <form method="post" 
            action="{{route('course.update', $course->id)}}" 
                          enctype="multipart/form-data">
                          {!! method_field('put') !!}
                        {{ csrf_field() }}

                <div id="acoes" class="col-md-12">
                    <div class="form-row">
                        <div class="form-group col-md-5">
                            <label for="inputCode">Codigo</label>
                            <input type="text" class="form-control" id="inputCode" name="code" value="{{$course->code or old('code')}}" required>
                        </div>
                        <div class="form-group col-md-7">
                        <label for="inputName">Titulo</label>
                        <input type="text" class="form-control" id="inputName" name="name" value="{{$course->name or old('name')}}" required>
                    </div>
                    </div>
                    <div class="form-group">
                        <label for="inputInstructor">Nome do Instrutor</label>
                        <input type="text" class="form-control" id="inputInstructor" name="instructor" value="{{$course->instructor or old('instructor')}}" required>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-5">
                            <label for="inputCreditHour">Carga Horaria</label>
                            <input type="number" min="0" class="form-control" id="inputCreditHour" name="credit_hour" value="{{$course->credit_hour or old('credit_hour')}}" required>
                        </div>
                        
                        <div class="form-group col-md-5">
                            <label for="inputPrice">Preço</label>
                            <!-- <input type="text" class="form-control" id="inputPrice" name="price" value="{{$course->price or old('price')}}" required> -->
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">R$</span>
                                </div>
                                <input type="number" min="0" class="form-control" id="inputPrice" name="price" value="{{$course->price or old('price')}}" required>
                                <div class="input-group-append">
                                    <span class="input-group-text">.00</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputDescription">Descrição do Curso</label>
                        <textarea class="form-control" id="inputDescription" rows="3" name="description" required>{{$course->description or old('description')}}</textarea>
                    </div>  
                </div>
                <div class="col-md-12">                   
                    <button type="reset" class="btn btn-danger">Limpar</button>
                    <button type="submit" class="btn btn-warning" id="black">Alterar</button>
                </div>

                <!-- <button type="submit" class="btn btn-primary">Submit</button> -->
            </form>
        </div>
@stop

resources/views/default.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Cursos</title>

        <!-- <link rel="../assets/css/bootstrap.min.css"> -->
        <!-- <link rel="stylesheet" href="../assets/css/bootstrap.min.css"> -->
        <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">

    </head>
    <body>
    <!-- <h1 class="text-center">Hello World</h1> -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top" role="navigation">
            <a class="navbar-brand" href="#">Cursos</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
        <div class="container">
            @yield('content')
        </div>
    <!-- <script src="../assets/js/jquery-3.3.1.min.js"></script>
    <script src="../assets/js/bootstrap.min.js"></script> -->
    <script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>
    <!-- <script src="{{ asset('js/myjs.js') }}"></script> -->
    </body>
</html>

resources/views/include-course.blade.php
@extends('default')

@section('content')
<div class="container-fluid">
            <hr/>
            <h3 class="page-item">Adicionar cursos</h3>
            <div class="col-md-12"
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ url('course/') }}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Adicionar</li>
                    </ol>
                </nav>
            </div>
            <hr/>
            <form method="post" 
                          action="{{route('course.store')}}" 
                          enctype="multipart/form-data">
                        {{ csrf_field() }}
                <div id="acoes" class="col-md-12">
                    <div class="form-row">
                        <div class="form-group col-md-5">
                            <label for="inputCode">Codigo</label>
                            <input type="text" class="form-control" id="inputCode" name="code" aria-describedby="codeHelp" placeholder="Digite o código">
                        </div>
                        <div class="form-group col-md-7">
                        <label for="inputName">Titulo</label>
                        <input type="text" class="form-control" id="inputName" name="name" aria-describedby="nameHelp" placeholder="Digite o título">
                    </div>
                    </div>
                    <div class="form-group">
                        <label for="inputInstructor">Nome do Instrutor</label>
                        <input type="text" class="form-control" id="inputInstructor" name="instructor" aria-describedby="instructorHelp" placeholder="Digite o nome do instrutor">
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-5">
                            <label for="inputCreditHour">Carga Horaria</label>
                            <input type="number" min="0" class="form-control" id="inputCreditHour" name="credit_hour" aria-describedby="creditHourHelp" placeholder="100">
                        </div>
                        
                        <div class="form-group col-md-5">
                            <label for="inputPrice">Preço</label>
                            <!-- <input type="text" class="form-control" id="inputPrice" name="price" aria-describedby="PriceHelp" placeholder="Digite o preço do Curso"> -->
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">R$</span>
                                </div>
                                <input type="number" min="0" class="form-control" aria-label="Amount (to the nearest dollar)" id="inputPrice" name="price" aria-describedby="PriceHelp" placeholder="00">
                                <div class="input-group-append">
                                    <span class="input-group-text">.00</span>
                                </div>
                            </div>
                        </div>
                        

                    </div>
                    <div class="form-group">
                        <label for="inputDescription">Descrição do Curso</label>
                        <textarea class="form-control" id="inputDescription" rows="3" name="description"></textarea>
                    </div>  
                </div>
                <div class="col-md-12">                   
                    <button type="reset" class="btn btn-danger">Limpar</button>
                    <button type="submit" class="btn btn-warning" id="black">Cadastrar</button>
                </div>

                <!-- <button type="submit" class="btn btn-primary">Submit</button> -->
            </form>
        </div>
@stop

resources/views/index.blade.php
<!-- <!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Cursos</title>

         <link rel="../assets/css/bootstrap.min.css"> 
        <link rel="stylesheet" href="../assets/css/bootstrap.min.css">

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top" role="navigation">
            <a class="navbar-brand" href="#">Cursos</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
        <h1 class="text-center">Tela Principal</h1>
        <script src="../assets/js/jquery-3.3.1.min.js"></script>
        <script src="../assets/js/bootstrap.min.js"></script>
    
    </body>
</html> -->



@extends('default')

@section('content')
    <h1>Cursos</h1>
    <a href="{{ url('course/create') }}">Adicionar</a>
    <!-- restante do conteúdo -->
@stop

resources/views/list-course.blade.php
@extends('default')

@section('content')
@if (session('message'))
    <div id="alertaMessage" class="alert alert-success alert-dismissible fade show" role="alert">
                {{ session('message') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
    </div>
@endif

<div class="container-fluid">
    <hr/>
    <div id="topo" class="row">
        <div class="col-md-10">
            <h2>Itens</h2>
        </div>
        <div class="col-md-2">
        <a class="btn btn-primary" href="{{ url('course/create') }}">Novo Curso</a>
        </div>
        <div class="col-md-12"
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Home</li>
                </ol>
            </nav>
        </div>
    </div>
    <hr/>
    <div id="lista" class="row">
        <div class="table-responsive col-md-12">
            <table class="table table-bordered table-striped" cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                    <th scope="col">Codigo</th>
                    <th scope="col">Titulo</th>
                    <th scope="col">Instrutor</th>
                    <th scope="col">CH</th>
                    <th scope="col">Preço</th>
                    <th scope="col">Descrição</th>
                    <th class="acoes" scope="col">Ações</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($courses as $course)   
                    <tr>
                    <th scope="row">{{$course->code}}</th>
                    <td>{{$course->name}}</td>
                    <td>{{$course->instructor}}</td>
                    <td>{{$course->credit_hour}}</td>
                    <td>{{$course->price}}</td>
                    <td>{{$course->description}}</td>
                    <td>
                    <a class="btn btn-warning btn-sm" href="{{route('course.edit', $course->id)}}">Editar</a>
                    &nbsp;<form style="display: inline-block;" method="POST" 
                                                        action="{{route('course.destroy', $course->id)}}"                                                        
                                                        data-toggle="tooltip" data-placement="top"
                                                        title="Excluir" 
                                                        onsubmit="return confirm('Confirma exclusão?')">
                                                {{method_field('DELETE')}}{{ csrf_field() }}     
                                                <button type="submit" class="btn btn-danger btn-sm">Excluir
                                                    </form>                                           
                                                </button>
                                                       
                    </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    
</div>

@stop